kcp-dev/helm-charts

- .github/workflows/release.yml
Simple one to use latest checkout action.
> ci: Use github checkout action v3

- charts/kcp/templates/etcd.yaml
- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
A number of changes to use kcp helm chart with an external etcd (to make maintenance easier when this is eventually ready for production), as well as removing configuration specific to the red hat environment. This PR also adds configuration to work with vanilla kubernetes via changes such as adding Ingress and Gateway configuration in addition to OpenShift Routes.
> Extra configuration

- charts/kcp/templates/etcd.yaml
- charts/kcp/templates/issuer.yaml
- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
Current cert-manager configuration had each intermediate CA actually act
as an independent root CA.  This change installs an actual root CA and
has all intermediate certs be signed by it (instead of themselves).
> Add proper CA certificate

- charts/kcp/Chart.yaml
- charts/kcp/templates/kcp.yaml
This flag needs to be added, otherwise now the VW url defaults to the
"base URL", which is *not* the external URL.
> Add --shard-virtual-workspace-url flag

- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
The images in Openshfit CI only include one binary per image, so we also
need to allow setting different image specs for each container.
The location of each binary is changing as well, though hopefully the
entrypoint can be used going forward (after the virtual-workspace
container removes its custom inline script).
> Use Openshift CI as image registry

- charts/kcp/templates/etcd.yaml
- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
Each of the following containers will have the parameter:
* kcp
* virtual-workspaces
* kcp-front-proxy
* etcd
Note that etcd does not have a configurable port
Fixes #15
> Make profiling containers a chart parameter

- charts/kcp/values.yaml
- remove CPU limits, they are not useful
- allow large memory limits, increase requests
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
> values: tune resources

- charts/kcp/values.yaml
This is a mistake introduced via #24 - we should
disable all ingress options by default, then users can choose one which suits their environment
> Don't enable openshiftRoute by default

- charts/kcp/templates/external-logical-cluster-admin-kubeconfig.yaml
- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
Currently the logical cluster admin kubeconfig is used to access both the [external front-proxy endpoint](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/tenancy/workspace/workspace_controller.go#L194..L195), and also the [shard directly via the baseURL](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/tenancy/workspace/workspace_reconcile.go#L71..L72) - this won't work in the case where different CA certs are used for shard and front-proxy such as in the templates maintained in this repo.
Requires https://github.com/kcp-dev/kcp/pull/2882
Fixes: #32
> Add external-logical-cluster-admin

- .gitignore
- README.md
- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
- hack/generate-admin-kubeconfig.sh
- hack/kind-setup.sh
- hack/kind-values.yaml
- hack/kind/config.yaml
In this PR:
1. Rename `readme.md` to `README.md` (sorry, nitpicking)
2. Add the ability to deploy with a token file
3. Remove lets encrypt production issuer as default (does not work well with kind)
4. Add helper script to deploy end-to-end kind cluster with self-signed certificates and localhost ingress (nginx)
> Auth token support + kind cluster helper

- charts/kcp/templates/etcd.yaml
- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
I've never seen the way that the `kcp` Helm chart configures resources. This updates `values.yaml` and affected templates to use a de-facto standard for Helm charts, used in popular Helm charts like [cert-manager](https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager) or [ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx).
> Standardize resource configuration

- charts/kcp/Chart.yaml
Low priority PR, but I figured it would be nice to publish some metadata as part of the Helm chart.
> Add chart metadata to Chart.yaml

- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
This PR adds what I mentioned over in the previous PR (https://github.com/kcp-dev/helm-charts/pull/38#discussion_r1253102023) to the kcp pod templates. I took the liberty to also enable seccomp profiles by default, a small security improvements usually recommended. I don't think kcp does any crazy syscalls that we would need to allow outside of seccomp.
The fsGroup is chosen based [on the kcp Dockerfile](https://github.com/kcp-dev/kcp/blob/ae902beedc1f45ec37afc87881f3f9d2473bf927/Dockerfile#L64) setting the image up to use this user and group ID by default. For some environments, this is a necessary setting so the mounted PVC gets reconfigured correctly.
> Add securityContexts to confine kcp pods and set fsGroup correctly

- charts/kcp/values.yaml
Because the kcp-front-proxy serves HTTPS by default, installing the chart without customizing the Ingress annotations will result in an error looking like
```
Client sent an HTTP request to an HTTPS server.
```
While this setting depends on the ingress controller in use, we already set `kubernetes.io/ingress.class=nginx`, so the general expectation of the default Helm values is that nginx-ingress-controller is deployed. Adding this annotation to the default set makes that implicit reference setup fully work.
In addition, this PR adds a comment so that users of other ingress controllers can look up what their implementation requires for similar functionality.
> set HTTPS backend annotation on Ingress resource by default

- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
The current options to expose the front proxy to the Internet are OpenShift Route, Ingress or Gateway. This PR adds some configuration that allows to reconfigure the `kcp-front-proxy` Service to be a load balancer directly.
To account for port changes, this PR also automatically reconfigures the `kcp` Deployment to make sure the Service port (8443) is respected for external URLs if `LoadBalancer` is chosen.
> add configuration options to `kcp-front-proxy` Service to expose it directly

- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
I keep forgetting that YAML does this - this fixes an issue I added in #45.
This produces failed upgrades with errors like this:
```
json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```
In addition, I committed the `type: LoadBalancer` change that was only meant for local testing. My bad, fixing this as well.
> 🐛  wrap EXTERNAL_PORT to make sure it's seen as string

- charts/kcp/templates/external-logical-cluster-admin-kubeconfig.yaml
When exporting the front proxy directly via a `LoadBalancer` service, this kubeconfig needs to be updated to use the correct external port. This matches the `EXTERNAL_PORT` environment variable set in the `kcp` Deployment, but we cannot read from it here, so we need to replicate the logic.
> change port in external-logical-cluster-admin kubeconfig when exposing front proxy directly

- charts/kcp/templates/kcp.yaml
- hack/kind-values.yaml
- hack/kind/config.yaml
Without this PR, setting `etcd.enabled` to `false` and `kcp.etcd.serverAddress` to `embedded` is not enough because it leaves the kcp server hanging due to the absence of the Secret named `kcp-etcd-client`, which is absent because the corresponding Certificate never gets that Secret issued, because it is asking for an issuer that does not exist due to the `etcd.enabled = false` setting.
This PR makes the dependence on the Secret named `kcp-etcd-client` go away if `kcp.etcd.serverAddress` is set to `embedded`, and adds the Certificate named `kcp-etcd-client` to the stuff that goes away if `etcd.enabled` is set to `false`.
Successfully tested with `etcd.enabled = false` and `kcp.etcd.serverAddress = "embedded"`.
Should also be functional with `etcd.enabled = false` and …
> Enable use of embedded etcd

- charts/kcp/templates/_helpers.tpl
- charts/kcp/templates/certmanagerissuer.yaml
- charts/kcp/templates/etcd.yaml
- charts/kcp/templates/external-logical-cluster-admin-kubeconfig.yaml
- charts/kcp/templates/front-proxy-kubeconfig.yaml
- charts/kcp/templates/issuer.yaml
- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
- charts/kcp/templates/lets-encrypt-ca.yaml
- charts/kcp/templates/logical-cluster-admin-kubeconfig.yaml
- charts/kcp/templates/rolebinding-edit-access.yaml
This PR updates the labels used for all resources created by this Helm chart to use [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) instead of the `app` label currently used on only a few resources (Deployments and StatefulSets) mostly.
Since this updates the label selectors, deleting the Deployments and StatefulSets before upgrading is required. Since we discussed that breaking changes are okay right now, I deemed that acceptable.
> Add well-known `app.kubernetes.io` labels to all resources

- charts/kcp/templates/kcp-front-proxy.yaml
- charts/kcp/templates/kcp.yaml
- charts/kcp/values.yaml
Since the `securityContext` I added to make the Helm chart work on vanilla Kubernetes is creating issues on OpenShift, this moves configuration for it to `values.yaml` file so we ship a sane default for (vanilla) Kubernetes users while allowing others to override settings as they require.
This is related to #52.
> Move security context to `values.yaml`

- .prow.yaml
- charts/kcp/templates/rolebinding-edit-access.yaml
My previous PR accidentally broke the chart because after rebasing I did not test it again.
This PR adds a presubmit job to prevent this from happening again.
> Add presubmit job to prevent chart from going bad

- charts/kcp/templates/etcd.yaml
In #53 I forgot to update the label selector in the `Service` object for etcd. This fixes that regression.
> Update service selector for etcd headless service

- charts/kcp/templates/kcp.yaml
After PKI cleanups done in #56, we are starting to see the effects of incorrect CAs used for certain `Certificates`. This is one of the cases:
`external-logical-cluster-admin-client-cert-for-kubeconfig` is used in the `external-logical-cluster-admin-kubeconfig` Secret as client certificate to access the kcp-front-proxy: https://github.com/kcp-dev/helm-charts/blob/f808f2b7c88736142137caea36ffd83ebd2e6197/charts/kcp/templates/external-logical-cluster-admin-kubeconfig.yaml#L16
But since the certificate is signed by `kcp-server-client-ca`, the front proxy will reject requests with this certificate, as it's using the `kcp-client-ca` to validate incoming client certificates:
https://github.com/kcp-dev/helm-charts/blob/f808f2b7c88736142137caea36ffd83ebd2e6197/charts/kcp/templates/kcp-front-proxy. …
> Use kcp-client-issuer for external-admin-kubeconfig certificate

- charts/kcp/templates/front-proxy-certificates.yaml
> Fix bug in front-proxy-certificates.yaml

- hack/generate-admin-kubeconfig.sh
- hack/kind-setup.sh
- hack/kind-values.yaml
- hack/kind/config.yaml
This PR updates the `kind-setup` script:
* re-indented the code
* Use yq instead of cat|grep|cut|tr.
* kind is only installed locally (no sudo required) and only if it's not existing (regardless of where the binary exists).
* The kind cluster was updated to 1.27.3 (with this release, the EphemeralContainer feature gate became GA and was removed).
* The script now provides a `kcp.kubeconfig` and a `kcp-kind.kubeconfig`.
* `kubectl rollout status` is used instead of a custom wait loop that greps for numbers.
* cert-manager was updated from 1.9.1 to 1.13.0.
* At the moment, kcp does not produce `latest` images anymore, so the script now allows to set `KCP_TAG` to override the version and actually install something recent (e.g. `KCP_TAG=bb5ce8f3 hack/kind-setup.sh`).
* The `/etc/hosts` …
> Improve kind scripting

- README.md
Looks like we were still referencing the issuer for client certificates for the kcp server. But we fixed CAs a while ago, so the client certificate should be issued by the dedicated `kcp-front-proxy-client-issuer`. 
[ref on #kcp-dev](https://kubernetes.slack.com/archives/C021U8WSAFK/p1700231520741799)
> 📖 use correct issuer for client certificates in README.md

- charts/kcp/Chart.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
Fixes #69.
This adds `kcp.batteries` to the chart's `values.yaml` and sets the `--batteries-included` flag on the `kcp` Deployment.
This will become useful with a future release of kcp that includes https://github.com/kcp-dev/kcp/pull/3041 (the `admin` battery) so we can disable writing `admin.kubeconfig`.
> ✨ Add `kcp.batteries` to `values.yaml` and set them on kcp deployment

- charts/kcp/Chart.yaml
- charts/kcp/templates/server-deployment.yaml
All the time back in #65, I made a mistake in the if condition guarding the `--etcd-servers` flag. `.kcp.etcd.enabled` doesn't exist, `etcd.enabled` does. This fixes that oversight. Because the flag wasn't set, **kcp was using the embedded etcd.**
⚠️ This is a breaking change because it will change the kcp server from using the embedded etcd as datastore to the external etcd StatefulSet that is part of the Helm chart. But this will seemingly wipe all data from your kcp instance.
If you want to retain data, you'll need to set `.kcp.etcd.serverAddress="embedded"` before upgrading.
> ⚠️ correctly check if etcd StatefulSet is enabled to set `--etcd-servers`

- charts/kcp/Chart.yaml
- charts/kcp/templates/server-deployment.yaml
I tried out `kcp.extraFlags` and figured out it wasn't working. This fixes it and processes the list correctly.
> 🐛 fix `kcp.extraFlags` being applied incorrectly

- charts/kcp/Chart.yaml
- charts/kcp/templates/front-proxy-deployment.yaml
- charts/kcp/values.yaml
This adds `kcpFrontProxy.extraFlags` which mirrors `kcp.extraFlags`, so that additional flags can be passed (e.g. for using https://github.com/kcp-dev/kcp/pull/3013).
> add kcpFrontProxy.extraFlags to pass additional flags to kcp-front-proxy Deployment

- .gitignore
- .prow.yaml
- hack/ci/render-helm-charts.sh
To further improve validation of PRs to this repository, I added [kubeconform](https://github.com/yannh/kubeconform) to our build image in https://github.com/kcp-dev/infra/pull/62.
This improves the `pull-helm-charts-render` Prow job by not just checking if Helm can render templates, but also if those rendered templates are valid Kubernetes resources.
> ✨ Add hack/ci/render-helm-charts.sh that improves validation

- .github/workflows/release.yml
This bumps the `helm/chart-releaser-action` to the latest available version ([v1.6.0](https://github.com/helm/chart-releaser-action)) and also enables `skip_existing`, an option that will prevent our GitHub Actions to fail on every commit we merge into `main` that doesn't bump the chart version.
> Update to helm/chart-releaser-action@v1.6.0 and skip releasing for existing versions

- charts/kcp/Chart.yaml
- charts/kcp/templates/front-proxy-deployment.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
This PR bumps the chart to use kcp [v0.22.0](https://github.com/kcp-dev/kcp/releases/tag/v0.22.0), which felt like a minor version bump for the chart version, hence the bump to v0.5.0 as well.
In addition, this PR picks up on some goodies we added in the new kcp release:
- Since generating the `admin.kubeconfig` and associated files is now hidden in the `admin` battery (which is not enabled in  the batteries of this helm chart), we can replace the PVC with an emptyDir. The `kcp` binary still complains if `/etc/kcp/config` does not exist, but it creates nothing in that directory. So I put a dummy volume with a size limit of 50Mi in there.
- This unlocks scaling the server deployment past the single replica we have been stuck with (if you also enable leader election, which I plan to …
> ✨ Update appVersion to 0.22.0 and eliminate server volume

- .gitignore
- charts/cache/Chart.yaml
- charts/cache/templates/_helpers.tpl
- charts/cache/templates/cache-deployment.yaml
- charts/cache/values.yaml
- charts/certificates/Chart.yaml
- charts/certificates/values.yaml
- charts/proxy/Chart.yaml
- charts/proxy/templates/front-proxy-deployment.yaml
- charts/proxy/values.yaml
- charts/shard/Chart.yaml
- charts/shard/values.yaml
- hack/ci/render-helm-charts.sh
This is probably not 100% cleaned up yet, but I added the new charts to the chart rendering script we run in CI to validate them. Publishing the last PR failed (see https://github.com/kcp-dev/helm-charts/commit/6c14e542c6d5ccd49887508e5eeffa8748b9af6f), so we need additional validation.
I found a couple of issues and missing fields in `values.yaml` of multiple charts that are expected to be there by the templates, so I've added them.
> Fix sharded charts to allow them to render successfully

- charts/kcp/Chart.yaml
Housekeeping for the Helm chart, we have released kcp [0.23.0](https://github.com/kcp-dev/kcp/releases/tag/v0.23.0) a while ago so this bumps the Helm chart to use that version. It's a prerequisite for #82 as that requires the metrics-viewer battery fix in kcp.
/cc @xrstf @mjudeikis
> ✨  Bump kcp version to 0.23.0

- charts/kcp/Chart.yaml
- charts/kcp/readme.md
- charts/kcp/templates/_helpers.tpl
- charts/kcp/templates/etcd-servicemonitor.yaml
- charts/kcp/templates/front-proxy-servicemonitor.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/templates/server-servicemonitor.yaml
- charts/kcp/values.yaml
This adds three `ServiceMonitor` objects that can be enabled to monitor the components deployed by the `kcp` Helm chart: etcd, kcp-front-proxy and kcp(-server).
> ✨  Add support for monitoring kcp with prometheus-operator

- charts/kcp/Chart.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/templates/server-kubeconfigs.yaml
- charts/kcp/values.yaml
Before this PR, the external port of the kcp server is set to 8443 for a `LoadBalancer` service type and 443 otherwise. The later is the case where an ingress is expected to be in-front of kcp. But when the actual usecase is to talk to the frontproxy directly via the service, this logic is wrong. Adding `.Values.externalPort` allows the customize the port, overriding upper logic.
> server-deployment: add .Values.externalPort to customize EXTERNAL_PORT

- charts/kcp/templates/etcd-pdb.yaml
- charts/kcp/templates/front-proxy-pdb.yaml
- charts/kcp/templates/server-pdb.yaml
- charts/kcp/values.yaml
- hack/kind-setup.sh
This PR adds an optional PodDisruptionBudget for KCP, front proxy, and etcd. This ensures that each component remains available during node draining/upgrades.
KCP server - if enabled, defaults to minAvailable = 1 
front proxy - same as KCP server. if enabled, defaults to minAvailable = 1 
etcd - if enabled, defaults to maxUnavailable = 1
Tested locally via updating the `./hack/kind-values.yaml`
```
diff --git a/hack/kind-values.yaml b/hack/kind-values.yaml
index b14c13f..0b8358c 100644
--- a/hack/kind-values.yaml
+++ b/hack/kind-values.yaml
@@ -1,14 +1,22 @@
externalHostname: "kcp.dev.local"
etcd:
-  enabled: false
+  enabled: true
+  podDisruptionBudget:
+    enabled: true
kcp:
+  replicas: 2
volumeClassName: "standard"
tokenAuth:
enabled: true
etcd:
-    serverAddress: embedded
+ …
```
> Add PodDisruptionBudgets for all KCP components

- README.md
- charts/kcp/Chart.yaml
- charts/kcp/templates/front-proxy-deployment.yaml
- charts/kcp/values.yaml
- hack/generate-admin-kubeconfig.sh
- hack/kind-setup.sh
- hack/kind-values.yaml
- hack/kind/config.yaml
This PR is a pretty big refresh to the kind setup because I was discussing it with an interested party and we just couldn't get the setup to work properly. I assume it has been broken in many ways for a while.
The changes in this PR are:
- Eliminate usage of an Ingress. If we are going to have a node port exposure via nginx-ingress-controller, might as well expose kcp directly. This switches the `kcp-front-proxy` Service to be of type `NodePort`.
- Make the `kcp-front-proxy` Service more configurable to pre-allocate a service IP and a specific node port, so we can hack in DNS entries (on the kcp Pod side) and node port forwards (on the `kind` side) pointing to the front proxy.
- Subsequently, this PR sets up a host alias in the kcp pod to make sure that traffic to the external name gets …
> Rework kind setup by removing Ingress and embedded etcd

- charts/kcp/Chart.yaml
We cut kcp [0.24.0](https://github.com/kcp-dev/kcp/releases/tag/v0.24.0) in April but never updated the Helm chart. Here's the PR to do that.
> Bump kcp AppVersion to 0.24.0

- .prow.yaml
We are running a quite old build image in this presubmit, this updates it to the latest available `ghcr.io/kcp-dev/infra/build` image. It includes an update to Helm 3.15.3.
> Update `pull-helm-charts-render` presubmit to `build:1.22.5-1` image

- charts/kcp/templates/etcd-statefulset.yaml
- charts/kcp/values.yaml
- charts/shard/templates/etcd-statefulset.yaml
Fixes: #72 
@mjudeikis do you want me to update the default etcd Helm value as well?
I verified the CLI flags to etcd stayed the same before and after, and that a StatefulSet upgrade to etcd version `v3.5.15` in Helm values worked 👍 
cc @sttts
> Don't make use of /bin/sh in etcd images & update etcd version

- charts/kcp/templates/etcd-statefulset.yaml
- charts/kcp/values.yaml
Currently, consumers of the KCP Helm chart are unable to specify a `StorageClass` to use with the Etcd `StatefulSet`. This isn't a big deal in local dev environments. However with larger deployments where you need different storage types (e.g. SSDs), this can be problematic unless you change the default storageclass for the cluster - which has it's own impacts.
This changeset enables specifying the `storageClassName` for the underlying `volumeClaimTemplate` via the values.yaml or Helm override arg. I've explicitly opted to only use the storageClassName property if it's been set in the values.yaml, rather than specifying a default value in the values.yaml file. That way the current behavior continues to work and operators that need a more advanced setting are enabled to specify the target …
> Allow for specifying storageClassName for etcd PVC

- charts/kcp/templates/front-proxy-ingress.yaml
I believe the `backend.service.name` targeted by the Ingress for the front-proxy should use the front-proxy's templated name, instead of having "kcp-front-proxy" hardcoded.
> fix front-proxy Ingress' backend service

- charts/kcp/Chart.yaml
We just released kcp 0.25.0 (https://github.com/kcp-dev/kcp/releases/tag/v0.25.0) so this bumps the Helm chart appropriately.
> kcp: update to kcp release 0.25.0

- charts/kcp/templates/front-proxy-servicemonitor.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/templates/server-kubeconfigs.yaml
- charts/kcp/values.yaml
The kcp chart allows passing a custom `kcpFrontProxy.certificateIssuer` to provide the front-proxy a server cert, instead of the default `kcp-server-issuer`. However, other parts of the chart (notably the front-proxy's ServiceMonitor and the external-admin-kubeconfig) were not properly reacting to this setting.
More precisely, here is the CA cert that should be used by components that try to reach the kcp-front-proxy:
- when no certificateIssuer is provided: the default kcp-ca
- when a *public* certificateIssuer is provided (e.g. LetsEncrypt): no CA
- when a custom *private* certificateIssuser is provided: the CA cert for that private issuer, referenced via `kcpFrontProxy.certificateIssuer.secret`
@embik should I extend this to also support providing the CA cert via a `ConfigMap`, instead …
> Use appropriate CA cert to reach the front-proxy

- charts/kcp/templates/etcd-statefulset.yaml
- charts/kcp/templates/front-proxy-deployment.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
This PR adds support for setting affinity rules. When running multiple replicas, this allows users to specify affinity settings such as podAntiAffinity to ensure that pods are scheduled on different nodes or apply custom node affinity configurations.
used `helm template` to ensure it renders the appropriate objects with and without affinity.
> Allow setting affinity

- charts/kcp/Chart.yaml
- charts/kcp/templates/server-deployment.yaml
Fixes https://github.com/kcp-dev/helm-charts/issues/103.
kcp-front-proxy sets the `X-Remote-` headers after validating a ServiceAccount token, but the kcp server wasn't accepting that header. This fixes that oversight, so now all extra auth information parsed by the front-proxy should be accepted by the kcp server.
Some of the information lost in the process was the clusterName that the ServiceAccount is coming from, which resulted in having to explicitly grant them access via RBAC if the ServiceAccount token was used against the front-proxy (but not against the server directly).
> Add X-Remote-Extra- headers prefix configuration

- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
Support for running with embedded etcd (a mode implemented in kcp for local development) has been added in #51. Unfortunately, it has been broken since #81 when I started eliminating the use of kcp's root directory for anything. A follow-up to that is currently in review at https://github.com/kcp-dev/kcp/pull/3158.
As per the [thread](https://kubernetes.slack.com/archives/C021U8WSAFK/p1720507955236309) on Slack, it seems we are in agreement that this shouldn't be supported anymore. It seems that no adopter is actually using it (since it's broken since beginning of the year) and it creates severe headache to running kcp as a Deployment.
> Remove support for embedded etcd in Chart

- charts/kcp/templates/front-proxy-ingress.yaml
- charts/kcp/values.yaml
The kubernetes.io/ingress.class annotation is deprecated since Kubernetes v1.18 (https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation).
This allows specifying an ingress class via the spec.ingressClassName field of the Ingress resource, and exposes a corresponding kcpFrontProxy.ingress.ingressClassName key in values.yaml.
Note: this should still be fully backwards-compatible. Users that for any reason still want to use the `kubernetes.io/ingress.class` annotation can always leave `ingressClassName` empty and rely on `kcpFrontProxy.ingress.annotations` just like before.
> front-proxy Ingress: add ingressClassName field

- charts/kcp/templates/etcd-certificates.yaml
- charts/kcp/templates/etcd-statefulset.yaml
- charts/kcp/values.yaml
I tried to set up kcp in a namespace that has istio injection enabled. Unfortunately, it wasn't working (mainly kcp couldn't talk to etcd over the istio-proxy connection) and threw some obscure error messages suggesting authentication failed.
The problem was actually that Istio couldn't detect the right protocol to proxy. I'm adding the `appProtocol` field to both service ports to ensure that Istio knows it has to proxy HTTPS. In addition, the (client) certificates needed to have `127.0.0.6` (the istio-proxy sidecar IP) injected so they'd be accepted by the servers. This PR therefore also adds the option to add more ip addresses to the generated certificates.
> Make etcd service more Istio-friendly

- charts/kcp/Chart.yaml
We just released https://github.com/kcp-dev/kcp/releases/tag/v0.26.0, time to update the Helm chart.
> Update appVersion to 0.26.0, Helm chart version to 0.9.0

- charts/kcp/templates/server-deployment.yaml
The root-ca must match the serving certs, in particular of the front-proxy.
Note: the shards server deployment is configured like in this PR already, just the single-shard mode is broken.
> server: wire kcp-ca as root-ca, ending up in service account token secrets

- charts/kcp/Chart.yaml
- charts/kcp/templates/server-deployment.yaml
https://github.com/kcp-dev/kcp/pull/3158 has made it possible to no longer have a defined root directory, so this PR removes the `emptyDir` hack we've had in place for some time and puts the root filesystem into read-only to make sure we don't write anything to the container filesystem by accident.
> Remove emptyDir from kcp Deployment, make root filesystem read-only

- charts/kcp/templates/front-proxy-deployment.yaml
When the `kcp` chart is used as dependency, the volume `kcp-token-auth-file` cannot be created from a hardcoded secret name `kcp-token-auth-file`, because the generated secret includes the name of the release. 
This change uses `kcp.fullname` template helper, similar to how the other secret names are referenced.
> fix (secret): kcp-token-auth-file

- charts/kcp/Chart.yaml
We are about to release 0.26.1, this is the PR to bump the appVersion.
Only merge after 0.26.1 release has been cut.
> [charts/kcp] Update kcp version to 0.26.1

- charts/api-syncagent/Chart.yaml
- charts/api-syncagent/LICENSE
- charts/api-syncagent/README.md
- charts/api-syncagent/templates/_helpers.tpl
- charts/api-syncagent/templates/deployment.yaml
- charts/api-syncagent/templates/rbac.yaml
- charts/api-syncagent/values.yaml
- hack/ci/render-helm-charts.sh
This adds a simple chart to deploy an instance of https://github.com/kcp-dev/api-syncagent.
fixes #120
> add basic chart for the new api-syncagent

- charts/api-syncagent/templates/crd-publishedresource.yaml
- charts/api-syncagent/values.yaml
- hack/ci/render-helm-charts.sh
This adds the current `PublishedResource` CRD from https://github.com/kcp-dev/api-syncagent into the Helm chart.
> Include PublishedResource CRD in api-syncagent Helm Chart

- charts/api-syncagent/Chart.yaml
- charts/api-syncagent/templates/_helpers.tpl
- charts/api-syncagent/templates/deployment.yaml
We just released api-syncagent [v0.1.0](https://github.com/kcp-dev/api-syncagent/releases/tag/v0.1.0) 🎉 
This brings the Helm chart to version 0.1.0, sets the proper appVersion and fixes image defaulting to the chart version. The used template honestly looks needlessly complex, the new snippet is what is also used in default templates generated by `helm` (see #126 for comparison).
> Update to api-syncagent 0.1.0 and bump chart

- charts/kcp-operator/.helmignore
- charts/kcp-operator/Chart.yaml
- charts/kcp-operator/LICENSE
- charts/kcp-operator/templates/_helpers.tpl
- charts/kcp-operator/templates/crds.yaml
- charts/kcp-operator/templates/deployment.yaml
- charts/kcp-operator/templates/rbac.yaml
- charts/kcp-operator/templates/service.yaml
- charts/kcp-operator/templates/serviceaccount.yaml
- charts/kcp-operator/values.yaml
Since https://github.com/kcp-dev/kcp-operator is slowly shaping up, here is a basic Helm chart that deploys kcp-operator.
Please note that this is highly experimental. Especially the CRDs and RBAC have been copied from the repository, and they will likely change a lot. It also notably does not yet up admission webhooks, since we haven't really created any webhooks in the upstream project.
> Add basic Helm chart for kcp-operator

- README.md
- charts/kcp/README.md
Since this repository is becoming a multi-chart repository (it always has been, but we haven't treated the multi-shard charts really well) with `kcp`, `api-syncagent` and soon `kcp-operator`, I would like to propose that we move content specific to the `kcp` chart out of the main repository README and into `charts/kcp/README.md`.
> Move chart-specific README content to chart README

- charts/kcp/Chart.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
This PR adds the ability to add `podAnnotations` to the server deployment to further configure its integration into other systems like e.g. istio
> feat(podAnnotations): allow for podAnnotations on kcp server deployment

- charts/kcp/Chart.yaml
- charts/kcp/templates/front-proxy-certificates.yaml
- charts/kcp/values.yaml
This feature is particularly useful when deploying into KCP via a tool like flux from a local kind cluster. Setting these additional dnsNames allows you for example to use the cluster internal service name in a kubeconfig to deploy with flux.
> feat: allow to configure extraDNSNames to be added to the frontproxy certificate

- charts/kcp/Chart.yaml
We just released kcp 0.27.1 which addressed an upgrade issue from 0.26, so it's time to bring the Helm chart up to this version.
> Update kcp chart to version 0.10.0 (appVersion 0.27.1)

- .gitignore
- charts/api-syncagent/templates/_helpers.tpl
- charts/api-syncagent/templates/deployment.yaml
- charts/api-syncagent/values.yaml
- charts/cache/templates/_helpers.tpl
- charts/cache/templates/cache-deployment.yaml
- charts/cache/values.yaml
- charts/kcp-operator/templates/_helpers.tpl
- charts/kcp-operator/templates/deployment.yaml
- charts/kcp-operator/values.yaml
- charts/kcp/templates/_helpers.tpl
- charts/kcp/templates/etcd-statefulset.yaml
- charts/kcp/templates/front-proxy-deployment.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
- charts/proxy/templates/_helpers.tpl
- charts/proxy/templates/front-proxy-deployment.yaml
- charts/proxy/values.yaml
- charts/shard/templates/_helpers.tpl
- charts/shard/templates/server-deployment.yaml
- charts/shard/values.yaml
When trying to use the provided helm charts in an air-gapped environment (or) with a private registry using authentication it will fail. This PR adds the ability to optionally provide imagePullSecrets for every chart.
Tested it on a local kind cluster and validated the Deployment manifests with and without providing imagePullSecrets.
> Add the ability to provide imagePullSecrets for private Registries or Registries with auth

- charts/kcp/templates/front-proxy-deployment.yaml
- charts/kcp/values.yaml
This PR will add the configuration to use pre-existing LoadBalancer IP addresses for the kcp-front-proxy service.
> Make LB IP configurable for kcp-front-proxy service

- charts/kcp-operator/Chart.yaml
- charts/kcp-operator/README.md
kcp-operator [v0.1.0](https://github.com/kcp-dev/kcp-operator/releases/tag/v0.1.0) is out. Let's bump the Helm chart accordingly.
> charts/kcp-operator: bump to initial release version v0.1.0

- README.md
- charts/kcp-operator/README.md
Extending the kcp-operator README a bit and adding a reference from the main repository README.
> Add kcp-operator to repository README and extend Chart README

- charts/kcp/Chart.yaml
- charts/kcp/README.md
- charts/kcp/templates/front-proxy-certificates.yaml
- charts/kcp/templates/letsencrypt-clusterissuers.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
Exposing kcp via `Ingress` only works with TLS passthrough, but this has neither been documented nor configured adequately in the default values. This PR addresses this and also fixes some templating issues as I've been trying to get Ingress + Let's Encrypt (a combination that seems to be chosen commonly) to work.
In addition, I've documented as much as I could regarding ingress method and Let's Encrypt certificates on kcp-front-proxy in an update to the README.md file for the chart.
_Also_, I took some time to add line breaks and some more comments to the `values.yaml` file, which makes it much more readable IMHO.
> kcp: require TLS passthrough for Ingress and improve README

- charts/kcp/Chart.yaml
- charts/kcp/templates/server-deployment.yaml
We should remove these `GOMEMLIMIT` and `GOMAXPROCS` environment variables, they limit practical resource usage to what is in requests (so no ability to hit container resource limits). @xrstf investigated high CPU usage (which was the cause for #105) and it turns out that this happens when there are too many workspaces in kcp and there is simply the need for more memory than the process can take right now (3 MBs per empty workspace is the rough estimate of memory usage).
> Remove Go runtime environment vars that pin resources to requests

- charts/kcp/Chart.yaml
This updates the `kcp` chart to use kcp [0.28.0](https://github.com/kcp-dev/kcp/releases/tag/v0.28.0).
> kcp: update to kcp 0.28.0

- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
This adds `kcp.leaderElection.enabled` to the available Helm chart values, which is set to `true` by default. Thus, we can enable rolling updates as kcp will now take a lock to determine whether it should start controllers or just serve API endpoints.
Closes #154.
> Enable leader election by default and configure RollingUpdate

- charts/kcp/Chart.yaml
- charts/kcp/templates/etcd-statefulset.yaml
- charts/kcp/templates/front-proxy-deployment.yaml
- charts/kcp/templates/server-deployment.yaml
- charts/kcp/values.yaml
This PR adds support for setting PriorityClassName on KCP components.
used `helm template` to ensure it renders the appropriate objects with and without PriorityClassName.
> feat: allow setting PriorityClassName on KCP components

- charts/kcp/Chart.yaml
kcp 0.28.1 is out, so let's update the chart accordingly.
Full changelog available here: https://github.com/kcp-dev/kcp/releases/tag/v0.28.1
> kcp: update to app version 0.28.1
